### ISSUE TITLE
Unsupported allele type

### ISSUE THREAD

**Issue by aksenia** [mlinderm/npsv#2]
After running the command (via Docker) as in the example: 

`Traceback (most recent call last):
  File "/usr/local/bin/npsv", line 33, in <module>
    sys.exit(load_entry_point('npsv==0.1.0', 'console_scripts', 'npsv')())
  File "/usr/local/lib/python3.6/dist-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/main.py", line 485, in main
    desc="Extracting features",
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/main.py", line 179, in ray_iterator
    yield ray.get(done[0])
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1564, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::simulate_and_extract() (pid=8322, ip=172.17.0.7)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "/usr/local/lib/python3.6/dist-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/main.py", line 256, in simulate_and_extract
    fasta_path, ref_contig, alt_contig = variant.synth_fasta(extract_args)
  File "/usr/local/lib/python3.6/dist-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/variant.py", line 175, in synth_fasta
    alt_seq = self._alt_seq(args.flank, ref_seq)
  File "/usr/local/lib/python3.6/dist-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/variant.py", line 407, in _alt_seq
    raise ValueError("Unsupported allele type")
ValueError: Unsupported allele type`

We use VCFv4.1, with ALT specified as either of `CNV, DUP, DUP:TANDEM, DEL, INS` or in notation of breakpoints, e.g. `[12:133040061[A` or as a sequence for a fully resolved breakpoint.

**Comment by mlinderm** [comment]
Unfortunately at the moment NPSV only supports DEL (symbolic or sequence resolved) and INS variant types. I have been experimenting with explicit support for DUP, but they could also be expressed as insertions for use with NPSV.

**Comment by aksenia** [comment]
That is clear! thanks again for the fast reply. I'll try to format DUPs as INS.
