### ISSUE TITLE
An error occurred after compilation

### ISSUE THREAD

**Issue by Yechao94** [mlinderm/npsv#3]
Hello, I got the following error after finishing compiling：
```
[ychhuang@vm-login02 bin]$ npsv -h
Traceback (most recent call last):
  File "./npsv", line 33, in <module>
    sys.exit(load_entry_point('npsv==0.1.0', 'console_scripts', 'npsv')())
  File "./npsv", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/main.py", line 7, in <module>
    from npsv.npsv_options import *
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/npsv_options.py", line 2, in <module>
    from .genotyper import GENOTYPING_MODES, CLASSIFIERS
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/genotyper.py", line 26, in <module>
    from .feature_extraction import Features
  File "/public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/feature_extraction.py", line 13, in <module>
    from npsv import npsva
ImportError: /public/home/fan_lab/ychhuang/miniconda3/envs/Npsv/lib/python3.6/site-packages/npsv-0.1.0-py3.6-linux-x86_64.egg/npsv/npsva.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6SeqLib9BamReader4OpenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
Could you help me find out what caused the error?

Version：
gcc version 7.5.0 (crosstool-NG 1.24.0.131_87df0e6_dirty)
Python 3.6.13 :: Anaconda, Inc.

Thanks.

**Comment by mlinderm** [comment]
I suspect that there is some kind of library compatibility related to C++11 compatibility (since the problem seems to be linking to `basic_string`). I have not encountered this error before but will look around. I am presuming you didn't run into any trouble building the package?

**Comment by Yechao94** [comment]
According to the installation steps，an error occurred：
```
c++: error: unrecognized command line option '-std=c++14'
```
and I solved it by install gcc v7.5 using conda.

After that, everything goes well when building the package.  But with the command, the above error will still occur.

**Comment by mlinderm** [comment]
I have been able to build locally from a fresh clone (albeit with gcc8 system compiler on Centos). I did run into another issue when building the bwa submodule that I just pushed a commit to fix. 

Which specific Conda package did you install so I can try to replicate that setup locally? I wonder if it is an issue with incompatible object files. Before you downloaded the Anaconda gcc package did it partially compile? That is were some of the files, and particularly the seqlib submodule, compiled with a different compiler?
